# This compose file is for demonstration only, do not use in prod.
version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_DB: "idp"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local